#! /bin/sh

#kill previous session
#pkill compton &
#pkill mpd &
#pkill guake &

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

sh ~/.fehbg

sxhkd &

~/.config/polybar/launch.sh &

#nitrogen --restore &

#sleep 1 &

compton -b --config ~/.config/compton/compton.conf &

float.sh &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

clipit &

nm-applet &

blueman-applet &

mpd &

blueman &

pamac-tray &

guake &

#wal -R &

#plank &

xidlehook --not-when-fullscreen --not-when-audio --timer normal 900 'i3-fancy-multimonitor' '' &

xfce4-power-manager &

bspc monitor DVI-D-0 -d 1 2 3 4
bspc monitor HDMI-0 -d 5
 

# monocle layout on desktop 2
bspc desktop '^1' --layout monocle
#bspc desktop '^3' --layout floating

bspc config border_width         3
bspc config window_gap           15

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focused_border_color  \#143A3D
bspc config active_border_color   \#143A3D
bspc config normal_border_color   \#2F343F
bspc config presel_feedback_color \#143A3D
bspc config focus_follows_pointer true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
#bspc config border_radius         10
#bspc config top_padding           30


bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Steam state=floating follow=on
bspc rule -a '*:xfce4-panel' state=floating
bspc rule -a File-roller state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a discord state=floating
bspc rule -a polybar focus=off layer=below

alacritty -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on

#bspc rule -a scratchpad sticky=on state=floating hidden=on
#kitty -c scratchpad -e ~/bin/scratch &





