#! /bin/sh

sxhkd &

~/.config/polybar/launch.sh &

sleep 1 &

compton -b --config ~/.config/compton/compton.conf &

nitrogen --restore &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

clipit &

nm-applet &

blueman-applet &

mpd &

pamac-tray &

xidlehook --not-when-fullscreen --not-when-audio --timer normal 900 'blurlock' '' &

bspc monitor DVI-D-0 -d 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5 

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focused_border_color  \#458588
bspc config active_border_color   \#458588
bspc config normal_border_color   \#98971A
bspc config presel_feedback_color \#458588
bspc config focus_follows_pointer true
bspc config border_radius         10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Uget-gtk state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Gthumb state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Lightdm-settings state=floating
bspc rule -a Steam state=floating follow=on

alacritty -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on

#bspc rule -a scratchpad sticky=on state=floating hidden=on
#kitty -c scratchpad -e ~/bin/scratch &
